server {
    server_name iqa-learning.eclo.info;

    root /var/www/iqa-learning;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(?:css|js|mjs|png|jpg|jpeg|gif|svg|ico|webp|woff2?)$ {
        try_files $uri =404;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    listen [::]:443 ssl ipv6only=on;
    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/iqa-learning.eclo.info/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/iqa-learning.eclo.info/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    listen 80;
    listen [::]:80;
    server_name iqa-learning.eclo.info;

    return 301 https://$host$request_uri;
}
